name: data_serializer
description: Portable Dart package to handle data serialization/deserialization efficiently, including a dynamic BytesBuffer to read/write data.
version: 1.0.4
homepage: https://github.com/gmpassos/data_serializer

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  base_codecs: ^1.0.1
  collection: ^1.15.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  dependency_validator: ^3.1.0
  coverage: ^1.0.3
