name: data_serializer
description: Portable Dart package to handle data serialization/deserialization efficiently, including a dynamic BytesBuffer to read/write data.
version: 1.1.0
homepage: https://github.com/gmpassos/data_serializer

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  base_codecs: ^1.0.1
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
  dependency_validator: ^3.2.3
  coverage: ^1.7.2
  path: ^1.9.0
