name: data_serializer
description: Portable Dart package to handle data serialization/deserialization efficiently, including a dynamic BytesBuffer to read/write data.
version: 1.0.10
homepage: https://github.com/gmpassos/data_serializer

environment:
  sdk: '>=2.18.4 <4.0.0'

dependencies:
  base_codecs: ^1.0.1
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.3
  dependency_validator: ^3.2.2
  coverage: ^1.6.3
  path: ^1.8.3
